# Generated by Django 3.0 on 2021-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0005_auto_20210424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegpro',
            name='impf',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vegpro',
            name='item_type',
            field=models.CharField(choices=[('vegetable', 'Vegetables'), ('fruit', 'Fruits')], max_length=10),
        ),
    ]
